objects:
    - type: plane
      position:
        - 0
        - 0
        - 0
      scale:
        - 1000
        - 1000
        - 1000
      physics: false
      color:
        - 0.5
        - 0.5
        - 0.5
    - type: plane
      position:
        - 0
        - 0
        - 0
      scale:
        - 1000
        - 1000
        - 1000
      physics: false
      color:
        - 0.5
        - 0.5
        - 0.5
